/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package museumvisitor

import java.io.InputStream
import java.util.*

class App(inputStream: InputStream) {
    private val input = Scanner(inputStream)
    private val visitorStateChangeListener = VisitorStateChangeListener()

    private val museumVisitor = MuseumVisitor(
        Museum(5, 5), ParserStrategy(), listOf(Report(), Place(), Move(), Right(), Left(), Leave()))
        .apply { listeners.add(visitorStateChangeListener) }

    fun commandLoop() {
        println("Welcome to Museum Visitor,\n you can place me in the museum and move me around\n" +
                " E.g. Command:\n place x,y,facing <north/south/east/west>\n" +
                " or 'move' forward or turn 'left' or 'right' or report location\nplace 0,0,north\n" +
                "To Leave the museum type 'Q'\n")
        try {
            while (input.hasNextLine()) {
                val command = museumVisitor.action(input.nextLine().trim());
                if (command?.command == Commands.QUIT){
                    break;
                }

                println(visitorStateChangeListener.output)
            }
        } catch (e: ExitException){
            println("exiting on command")
        }
        finally {
            println("exiting!")
        }
    }

}

fun main() {
    val app = App(System.`in`)

    app.commandLoop()
}
