/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package museumvisitor

import java.io.InputStream
import java.util.*

class App(inputStream: InputStream) {
    private val input = Scanner(inputStream)
    private val visitorStateChangeListener = VisitorStateChangeListener()

    private val museumVisitor = MuseumVisitor(
        Table(5, 5), ParserStrategy(), listOf<Command>(Report(), Place(), Move(), Right(), Left()))
        .apply { listeners.add(visitorStateChangeListener) }

    fun commandLoop() {
        println("Welcome to Museum Visitor, you can place me on a table and move me around:\n place x,y,facing <north/south/east/west> or move or left or right or report\nplace 0,0,north ")
        try {
            while (input.hasNextLine()) {
                museumVisitor.action(input.nextLine())

                println(visitorStateChangeListener.output)
            }
        } finally {
            println("exiting!")
        }
    }

}

fun main(args: Array<String>) {
    val app = App(System.`in`)

    app.commandLoop()
}
