/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package museumvisitor

import java.io.InputStream
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App(InputStream.nullInputStream())
        assertNotNull(classUnderTest.commandLoop(), "app should have a greeting")
    }
}
